aula: Aula Magna
aula: Aula A
aula: Aula B
aula: Aula C
aula: Laboratorio Vela
aula: Laboratorio Via Sacchi
anno: 1° anno laurea triennale
anno: 2° anno laurea triennale
anno: 2° anno laurea triennale - INGEGNERIA
anno: 2° anno laurea triennale - SCIENZE
anno: 3° anno laurea triennale
anno: 3° anno laurea triennale - INGEGNERIA
anno: 3° anno laurea triennale - SCIENZE
anno: 3° anno laurea triennale - OPZIONALI
anno: 1° anno laurea magistrale
anno: 2° anno laurea magistrale - OPZIONALI
prof: Martina Magnani
prof: Giulio Scassa
prof: Filippo Ghinelli